[package]
name = "bevycraft_world"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
bevycraft_core.workspace = true

bevy.workspace = true

const-builder.workspace = true

rkyv.workspace = true